export const BasketballPlayers = [
    {
        name: 'Jovan Jovanovic',
        age: 14,
        sport: 'basketball',
        position: 'center',
        points: 120,
        asists: 40,
        rebounds: 90,
        games: 10,
        average_points: points / games,
        average_asists: asists / games,
        average_rebounds: rebounds / games,
    },
    {
        name: 'Petar Petrovic',
        age: 12,
        sport: 'basketball',
        position: 'back shooter',
        points: 150,
        asists: 20,
        rebounds: 40,
        games: 10,
        average_points: points / games,
        average_asists: asists / games,
        average_rebounds: rebounds / games,
    },
    {
        name: 'Janko Jankovic',
        age: 11,
        sport: 'basketball',
        position: 'playmaker',
        points: 110,
        asists: 60,
        rebounds: 40,
        games: 10,
        average_points: points / games,
        average_asists: asists / games,
        average_rebounds: rebounds / games,
    },
];

export const FootballPlayers = [
    {
        name: 'Dragan Dragic',
        age: 14,
        sport: 'football',
        position: 'center back',
        goals: 3,
        games: 10,
        average_goals: goals / games,
    },
    {
        name: 'Filip Filipovic',
        age: 12,
        sport: 'football',
        position: 'left winger',
        goals: 12,
        games: 10,
        average_goals: goals / games,
    },
    {
        name: 'Djordje Djordjevic',
        age: 11,
        sport: 'football',
        position: 'striker',
        goals: 14,
        games: 10,
        average_goals: goals / games,
    },
];

export const VolletballPlayers = [
    {
        name: 'Jovan Jovanovic',
        age: 14,
        sport: 'volleyball',
        position: 'blocker',
        points: 120,
        games: 10,
        average: points / games,
    },
    {
        name: 'Petar Petrovic',
        age: 12,
        sport: 'volleyball',
        position: 'right side hitter',
        points: 150,
        games: 10,
        average: points / games,
    },
    {
        name: 'Janko Jankovic',
        age: 11,
        sport: 'volleyball',
        position: 'libero',
        points: 110,
        games: 10,
        average: points / games,
    },
];
